version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: prometheus.home.lan
      VIRTUAL_PORT: 9090
    expose:
      - 9090

  blackbox_exporter:
    image: prom/blackbox-exporter
    volumes:
      - ./config/blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - 9115:9115
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: blackbox.home.lan
      VIRTUAL_PORT: 9115
    expose:
      - 9115

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    command:
      - '--collector.systemd'
      - '--collector.processes'
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: nodeexporter.home.lan
      VIRTUAL_PORT: 9100
    expose:
      - 9100

  grafana:
    image: grafana/grafana
    environment:
      VIRTUAL_HOST: grafana.home.lan
      VIRTUAL_PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - ./config/grafana.ini
    expose:
      - 3000
    restart: unless-stopped

  pihole_exporter:
    image: ekofr/pihole-exporter:latest
    environment:
      PIHOLE_API_TOKEN: "${PIHOLE_API_TOKEN:?err}"
      PIHOLE_HOSTNAME: "${PIHOLE_HOSTNAME:?err}"
      PIHOLE_PORT: "${PIHOLE_PORT:?err}"
      VIRTUAL_HOST: piexporter.home.lan
      VIRTUAL_PORT: 9617
    ports:
      - 9617:9617
    expose:
      - 9617

  cadvisor:
    image: gcr.io/cadvisor/cadvisor@sha256:9360d7421c5e9b646ea13e5ced3f8e6da80017b0144733a04b7401dd8c01a5cb
    environment:
      VIRTUAL_HOST: cadvisor.home.lan
      VIRTUAL_PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # Windows
      # - /mnt/windows_docker/:/rootfs/var/lib/docker:ro
    expose:
      - 8080
volumes:
  grafana-data: {}
  prometheus-data: {}

networks:
  default:
    name: nginx-proxy
    external: true
