version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    restart: unless-stopped

  blackbox_exporter:
    image: prom/blackbox-exporter
    volumes:
      - ./config/blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - 9115:9115
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - ./config/grafana.ini
    restart: unless-stopped

  container_exporter:
    image: prom/container-exporter
    ports:
      - 9104:9104
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  pihole_exporter:
    image: ekofr/pihole-exporter:latest
    environment:
      PIHOLE_API_TOKEN: "${PIHOLE_API_TOKEN:?err}"
      PIHOLE_HOSTNAME: "${PIHOLE_HOSTNAME:?err}"
      PIHOLE_PORT: "${PIHOLE_PORT:?err}"
    ports:
      - 9617:9617

volumes:
  grafana-data: {}
  prometheus-data: {}
