FROM busybox

ARG ARCH="amd64"
ARG OS="linux"
ARG ADGUARD_USERNAME
ARG ADGUARD_PASSWORD
ARG ADGUARD_PORT
ARG ADGUARD_HOSTNAME


ADD "https://github.com/dequeues/adguard-exporter/releases/download/rel/adguard_exporter-linux-arm" ./adguard_exporter

RUN ls
#COPY ["/tmp/adguard_exporter", "/bin/adguard_exporter"]

#RUN "chmod +x ./adguard_exporter"
RUN ["chmod", "+x", "./adguard_exporter"]
EXPOSE 9617

ENTRYPOINT ["./adguard_exporter"]
CMD ["-adguard_username", $ADGUARD_USERNAME, "-adguard_password", $ADGUARD_PASSWORD, "-adguard_port", $ADGUARD_PORT, "-adguard_hostname", $ADGUARD_HOSTNAME]
